CREATE TRIGGER failed_payment
AFTER UPDATE OR INSERT ON PAYMENT
FOR EACH ROW
EXECUTE PROCEDURE procedure_failed_payment();

CREATE OR REPLACE FUNCTION create_user_role()
RETURNS TRIGGER AS $$
BEGIN
CREATE ROLE NEW.email
LOGIN WITH PASSWORD NEW.passkey;


  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER create_user_role_trigger
AFTER INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION create_user_role();
