CREATE TRIGGER failed_payment
AFTER UPDATE OR INSERT ON PAYMENT
FOR EACH ROW
EXECUTE PROCEDURE procedure_failed_payment();

CREATE TRIGGER add_new_user
AFTER INSERT ON customer
FOR EACH ROW
EXECUTE FUNCION role_creation();

